#!/bin/bash
F=xtdiag_ki3v

BASE=`dirname $0`

export BREAK=${BREAK:-marchu_1seg_nostack marchu_4k}
export SECTS=".lib .text .resetvec .rodata"

# nasm -f dbg -iinc $F.asm -o $F.i -l $F.lst || exit -1
nasm -iinc $F.asm -o $F.8k -l $F.lst -Lb || exit -1
$BASE/size $F.map
$BASE/makerom $F.8k > $F.32k || exit -1

# set up a debugscript with breakpoints
$BASE/make_debugscript $F.map > $F.debug || exit -1
sha1sum $F.32k
echo

# code: language=bash tabSize=8
