#!/bin/bash
BASE=`dirname $0`
$BASE/build || exit -1

# if [ "x$DEBUG" == "x" ]; then
# 	DEBUG=''
# else
# 	DEBUG='-debug'
# fi

RAM=${RAM:-256K}
VIDEO=${VIDEO:-cga}
# HARDWARE='-isa1 mda'
# HARDWARE='-isa1 vga'

MOPTS="ibm5160 -isa1 $VIDEO -bios rev1 -ramsize $RAM"
VOPTS="-window -resolution 1280x800 -nofilter -nokeepaspect"
ROPTS="-skip_gameinfo -cheat -uimodekey END -nomouse -volume -20"
DOPTS="-debugger_font 'JetBrains-Mono' -debugger_font_size 14 -update_in_pause"
# LOPTS="-autoboot_script mamedebug.lua"
COPTS="-debugscript xtramtest.debug"

set -x
rm -f comments/ibm5160.cmt
mame $MOPTS -rompath ./roms $ROPTS $DOPTS $VOPTS $COPTS $LOPTS $*