#!/bin/bash
BASE=`dirname $0`
$BASE/build || exit -1

# if [ "x$DEBUG" == "x" ]; then
# 	DEBUG=''
# else
# 	DEBUG='-debug'
# fi

RAM=${RAM:-256}
CYCLES=${CYCLES:-4000}
# HARDWARE='-isa1 mda'
# HARDWARE='-isa1 vga'

set -x
# rm -f comments/ibm5160.cmt
# mame $MOPTS -rompath ./roms $ROPTS $DOPTS $VOPTS $COPTS $LOPTS $*
# cp xtramtest.8k bios.bin
dosbox-x -conf dosbox-x.conf --set "dosbox memsizekb=$RAM" --set "cpu cycles=$CYCLES" $* 2>/dev/null
# dosbox-x -conf dosbox-x.conf --set "dosbox memsizekb=$RAM" -c 'mount m .' -c 'boot --bios m:bios.bin' --set "cpu cycles=$CYCLES" $* 2>/dev/null
# rm bios.bin